AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  IndentationWidth: 4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '*.rake'
    - 'Rakefile'

Style/IndentArray:
  IndentationWidth: 4

Style/IndentHash:
  IndentationWidth: 4

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/SignalException:
  EnforcedStyle: semantic
